# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      with:
          persist-credentials: false
    
    - name: Clean Install dependencies and Build
      run: |
          yarn install --network-timeout 1000000
          rm -rf build
          yarn build
    
    - name: Run linters ✅
      uses: wearerequired/lint-action@v1
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Enable linters
          eslint: true
          prettier: true
    
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
          name: build
          path: build
